#!/bin/sh

export TARGET=i686-pc-dayos
export PREFIX=$PWD/rootsys
export PATH=$PATH:$PREFIX

if [ ! -d "rootsys" ]; then
	mkdir rootsys
	mkdir -p rootsys/usr/
	mkdir -p rootsys/image
fi

## Bootstrap libdayos and crt0
if [ ! -d "dayoslibs-build" ]; then
	mkdir dayoslibs-build
fi

cd dayoslibs-build
cmake ../DayOSLibraries/ -DDAYOS_KERNEL_INCLUDE=$PWD/../DayOSKernel/sys 
-DCMAKE_INSTALL_PREFIX=$PREFIX

make -j8
make install
cd ..

cp -r DayOS/kernel/sys/* rootsys/usr/include
if [ ! -d "build-gcc" ]; then
	mkdir build-gcc
fi

if [ ! -d "build-binutils" ]; then
	mkdir build-binutils
fi

cd build-binutils
../binutils-2.25/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
make -j8
make install
cd ..

cd build-gcc
../gcc-5.3.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++ --without-headers --with-sysroot=$PREFIX
make -j8
make install
cd ..

ln $PREFIX/i686-pc-dayos/lib/libstdc++.a $PREFIX/usr/lib
ln $PREFIX/i686-pc-dayos/lib/libsupc++.a $PREFIX/usr/lib

rm -rf build-gcc
rm -rf build-binutils
rm -rf dayoslibs-build
