SET(CMAKE_SYSTEM_NAME DayOS)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER ${CMAKE_INSTALL_PREFIX}/bin/i686-pc-dayos-gcc)
SET(CMAKE_CXX_COMPILER ${CMAKE_INSTALL_PREFIX}/bin/i686-pc-dayos-g++)

SET(CMAKE_FIND_ROOT_PATH  ${CMAKE_INSTALL_PREFIX}/image)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
